name: ffmri-env 
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.23.5
  - pandas=1.5.3
  - scikit-image=0.19.3
  - seaborn=0.12.2
  - matplotlib=3.6.3
  - nibabel=5.0.1
  - nipype=1.8.5
  - SimpleITK=2.2.1
  - scikit-learn=1.1.3
  - statsmodels=0.13.5
  - plotly=5.11.0
  - networkx=2.8.8
  - pytz=2022.7
  - requests-oauthlib=1.3.1
  - tenacity=8.1.0
  - retrying=1.3.3
  - loguru=0.6.0
  - patsy=0.5.3
  - protobuf=3.20.1
  - pyasn1-modules=0.2.8
  - imageio=2.22.4
  - tifffile=2022.10.10
  - webcolors=1.12
  - pip
  - pip:
      - antspyx==0.4.2  
